ArtPostings/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArtPostings.Models;


namespace ArtPostings.Controllers
{
    public class AboutController : Controller
    {
        private readonly IPostingService service;
        public AboutController(IPostingService _service)
        {
            service = _service;
        }
        
        // GET: About
        public ActionResult Index()
        {
            ViewBag.Mode = "_noItemDisplay";
            return View();
        }
    }
}

ArtPostings/Controllers/ArchiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArtPostings.Models;

namespace ArtPostings.Controllers
{
    public class ArchiveController : Controller
    {
        private readonly IPostingService service;
        public ArchiveController(IPostingService _service)
        {
            service = _service;
        }

        // GET: Archive
        public ActionResult Index()
        {
            setItemInfo();
            return View(service.ArchivePostings());
        }
        public ActionResult Reload()
        {
            setItemInfo();
            return PartialView("_itemDisplay", service.ArchivePostings());
        }
        public ActionResult Edit(int id)
        {
            setItemInfo();
            return PartialView("_itemDisplay", service.EditModeArchivePostings(id));
        }
        private void setItemInfo()
        {
            ViewBag.Blurb = service.ArchiveText;
            ViewBag.Header = service.ArchiveHeader;
            ViewBag.Mode = "_itemDisplay";
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ExtendedJsonResult Edit([Bind(Include = "Editing, ItemPosting")]ItemPostingViewModel posting)
        {
            setItemInfo();
            ChangeResult result = service.SaveArchiveChanges(posting);
            return new ExtendedJsonResult(result) { StatusCode = result.StatusCode };
        }
    }
}

ArtPostings/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArtPostings.Models;

namespace ArtPostings.Controllers
{
    public class LinksController : Controller
    {
        private readonly IPostingService service;
        public LinksController(IPostingService _service)
        {
            service = _service;
        }
        
        // GET: Links
        public ActionResult Index()
        {
            ViewBag.Blurb = service.ShopText;
            ViewBag.Mode = "_noItemDisplay";
            return View();
        }
    }
}

ArtPostings/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns#">
    <meta charset="utf-8" />
    <title>Ann Chambers Art</title>
    <meta property="og:title" content="Ann Chambers Art" />
    <meta property="og:image" content="http://annchambers.net/Content/art/aaa_thumb.JPG" />
    <meta property="og:site_name" content="Acylic and oil paintings by Ann Chambers" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lightbox.css")" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" media="screen" href="http://code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css" />
    <script src="@Url.Content("~/Scripts/jquery-1.11.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.8.3.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="../../Scripts/lightbox.min.js" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryajax")
    @Scripts.Render("~/bundles/bootstrap")    
    <meta name="description" content="Abstract art, Representational art" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />    
</head>
<body class='@(ViewBag.Admin != null ? "admin" : "general")'>
    <div id="page">
        <div class="top">
            <ul class="toprightmenu">
                @Html.Partial("_LoginPartial")
            </ul>
            <ul class="topleftmenu">
                <li><a href='@Url.Action("Index", "About")'>About</a></li>
                <li><a href='@Url.Action("Index", "Links")'>Links</a></li>
                <li><a href='@Url.Action("Index", "Archive")' id="dropzone-archive" ondrop="drop_here({ event: event, archive: true, display: true })" ondragover="allow_drop_here(event)">Archive</a></li>
                @*<li><a href='@Url.Action("Index", "Viewing")'>Viewing</a></li>*@
                <li><a href='@Url.Action("Index", "Contact")'>Contact</a></li>
                <li><a href='@Url.Action("Index", "Home")' id="dropzone-home" ondrop="drop_here({ event: event, archive: false, display: true })" ondragover="allow_drop_here(event)">Home</a></li>
            </ul>
        </div>
        <div id="main">
            <h1 class="main">Ann Chambers Art</h1><br />
            <div id="maintain">This website is undergoing maintenance</div>
            <div id="inner">
                <div id="listpad">
                    @if (ViewBag.Mode == "_itemDisplay")
            { @Html.Partial("_itemDisplay")}
            </div>
            <div class="notepad">
                <section>
                    @RenderSection("scripts", required: false)
                    @RenderBody()
                </section>
            </div>
        </div>
    </div>
</div>
</body>
</html>

ArtPostings/Views/Shared/_archive.cshtml
   <table class="main">
    <tr>
     <td><hr /></td>
    </tr>
    <tr>
     <td><div class="head">
     Paintings are acrylic or oil. Click on any painting for a larger image. © Copyright Ann Chambers 2012</div></td>
    </tr>
    <tr>
     <td><hr /></td>
    </tr>
       @Html.Partial("_postingList")
   </table>    

ArtPostings/Views/Shared/_itemDisplay.cshtml
<table id="items">
    <tr>
        <td><hr /></td>
    </tr>
    <tr>
        <td>
            <div class="boldhead">
                @ViewBag.Header
            </div>
            <div class="head">
                @ViewBag.Blurb
            </div>
        </td>
    </tr>
    <tr>
        <td><hr /></td>
    </tr>
                @{var partialView = (User.Identity.IsAuthenticated) ? "_postingEditList" : "_postingDisplayList";
            Html.RenderPartial(partialView);}
    
</table>

ArtPostings/Views/Shared/_postingDisplayItem.cshtml
<script>
    function openEdit(event, postingId) {
        event.preventDefault();
        $.ajax({
            url: '@Url.Action("Edit")', // controller-agnostic: this might call either the Archive or Home versions of 'Reload'
            data: {id: postingId},
            type: 'GET',
            cache: false, // Internet Explorer needs this or it will not show the results of recent saves when editing
            success: function (htmlstring) {
                // need to replace content at a fairly high level to ensure old postings are cleared out of the view
                $('#listpad').html(htmlstring);
                $('#listpad').show();
            },
            error: function (request, status, error) {
                alert(error);
            }
        });
    };
</script>
<td class="picturecell">
    <a class='picturelink' href=@Model.ItemPosting.FilePath rel='lightbox' title=@Model.ItemPosting.Title>
        <img alt=@Model.ItemPosting.ShortName width='120' title=@Model.ItemPosting.ShortName src=@Model.ItemPosting.FilePath />
    </a>
</td>
<td class="itemtext">
    <div class="itemheader">
        <strong>
            @Model.ItemPosting.Header
        </strong>
        <div class="itemaction">
            @*using two different techniques for ajax call to controllers (so that I remember how to do both - MCC):
                (1) next line, and (2) the JS function call at the head of _postingEditList*@
            @*<a href="@Url.Action("Edit", new { id = Model.ItemPosting.Id })" data-ajax='true' data-ajax-update='#listitems' data-ajax-mode='replace'>*@
            <a class="icon" href="#">
                <span class="ion-edit" onclick="openEdit(event, @Model.ItemPosting.Id)" data-pack="default" data-tags="talk" data-toggle="tooltip" title="Edit"></span>
            </a>
        </div>
    </div>
    <div class="itemdesc">@Model.ItemPosting.Description</div><br /><br />
    <div class="itemfooter"> @Model.ItemPosting.Price | Size :@Model.ItemPosting.Size</div>
</td>

ArtPostings/Views/Shared/_postingDisplayList.cshtml
@model IEnumerable<ArtPostings.Models.ItemPostingViewModel>
    @foreach (ArtPostings.Models.ItemPostingViewModel posting in Model)
    {
    <tr>
        <td>
            <table class="posting">
                <tr>
                    <td class="picturecell">
                        <a class="picturelink" href=@posting.ItemPosting.FilePath rel="lightbox" title=@posting.ItemPosting.Header>
                            <img alt=@posting.ItemPosting.ShortName width="120" title=@posting.ItemPosting.Title src=@posting.ItemPosting.FilePath />
                        </a>
                    </td>
                    <td class="itemtext">
                        <div class="itemheader">
                            <strong>@posting.ItemPosting.Header</strong>
                        </div>
                        <div class="itemdesc">@posting.ItemPosting.Description</div><br /><br />
                        <div class="itemfooter"> @posting.ItemPosting.Price | Size :@posting.ItemPosting.Size</div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <hr />
        </td>
    </tr>
    }

ArtPostings/Views/Shared/_postingEditItem.cshtml
@Html.EditorForModel()

ArtPostings/Views/Shared/_postingEditList.cshtml
@foreach (ArtPostings.Models.ItemPostingViewModel posting in Model)
{
    <tr>
        <td>
            <table class="posting">
                <tr>
                    @{ if (posting.Editing)
                        {
                            Html.RenderPartial("_postingEditItem", posting);
                        }
                        else
                        {
                            Html.RenderPartial("_postingDisplayItem", posting);
                        }
                    }
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <hr />
        </td>
    </tr>}

ArtPostings/Views/Shared/_shopwindow.cshtml
   <table class="main">
    <tr>
     <td><hr /></td>
    </tr>
    <tr>
     <td><div class="head">
     Paintings are acrylic or oil. Click on any painting for a larger image. Please note, prices quoted for all items 
     do not include postage and packing costs, which would be by arrangement. © Copyright Ann Chambers 2014</div></td>
    </tr>
    <tr>
     <td><hr /></td>
    </tr>
       @Html.Partial("_postingList")
   </table>    